export { Doc } from './document/Doc'
export { GlobalConfig } from './document/GlobalConfig'
export { Post } from './document/Post'
export { Example } from './document/Example'
export { Mdx } from './document/Mdx'
export { Compo} from './document/Compo'
export { Tutorial} from './document/Tutorial'