// NOTE This file is auto-generated by the Contentlayer CLI

import { type Post, type DocumentTypes } from './types'

export type * from './types'

export declare const allPosts: Post[]

export declare const allDocuments: DocumentTypes[]
